:sectanchors:
:stem: latexmath
:toc:

= Definitions

ifeval::["{docname}{outfilesuffix}" == "definitions.html"]
++++
include::../assets/navigation.htm[]
++++
endif::[]

== Maximum and Minimum Values


=== The extreme Value Theorem
****
If stem:[f] is continuous on a closed interval stem:[\lbrack a, b \rbrack], then stem:[f] attains an absolute maximum value stem:[f(c)] and an absolute minimum value stem:[f(d)] at some numbers stem:[c] and stem:[d] in stem:[\lbrack a, b \rbrack].
****

=== Fermat’s Theorem

.Fermat’s Theorem
****
If stem:[f] has a local maximum or minimum at stem:[c], and if stem:[f^\prime(c)] exists, then stem:[f^\prime(c) = 0].
****

**In terms of critical numbers, Fermat’s Theorem can be rephrased as follows:**

.Fermat’s Theorem (in terms of critical numbers)
****
If f has a local maximum or minimum at c, then c is a critical number of f.
****

=== Critical Number

A critical number of a function stem:[f] is a number stem:[c] in the domain of stem:[f] such that either stem:[f^\prime(c) = 0] or stem:[f^\prime(c)] does not exist.


To find an absolute maximum or minimum of a continuous function on a closed interval, we note that either it is local [in which case it occurs at a critical number by (7)] or it occurs at an endpoint of the interval, as we see from the examples in Figure 8. Thus the following three-step procedure always works. **See The Closed Interval Method.**

[#the-closed-interval-method]
=== The Closed Interval Method

****
To find the absolute maximum and minimum values of a continuous function stem:[f] on a closed interval stem:[\lbrack a, b \rbrack]:

1. Find the values of stem:[f] at the critical numbers of stem:[f] in stem:[(a, b)].
    - I.e. *critical numbers* of stem:[f] occur when stem:[f^\prime(c) = 0],
2. Find the values of stem:[f] at the endpoints of the interval.
    - I.e. stem:[f(a)] and stem:[f(b)].
3. The largest of the values from Steps 1 and 2 is the absolute maximum value; the smallest of these values is the absolute minimum value.
****

I.e. the maximum of stem:[f^\prime(c) = 0] and stem:[f(a)], stem:[f(b)].

Using sudo code, the <<The Closed Interval Method>> can be defined as the result of:
[latexmath]
++++
max \lbrack f(a), f^\prime(c) = 0, f(b) \rbrack
++++

