:sectanchors:
:stem: latexmath
:toc:

= Definitions

ifeval::["{docname}{outfilesuffix}" == "definitions.html"]
++++
include::../assets/navigation.htm[]
++++
endif::[]

== Secant line

[quote, 'https://en.wikipedia.org/wiki/Secant_line[Wikipedia:Secant_line]']
____
In geometry, a secant of a curve is a line that intersects the curve at a minimum of two distinct points.[1] The word secant comes from the Latin word secare, meaning to cut. In the case of a circle, a secant will intersect the circle at exactly two points.
____

[latexmath]
++++
include::assets/secant-line.tex[]
++++

== Tangent

[quote, 'https://en.wikipedia.org/wiki/Tangent[Wikipedia:Tangent]']
____
In geometry, the tangent line (or simply tangent) to a plane curve at a given point is the straight line that "just touches" the curve at that point. Leibniz defined it as the line through a pair of infinitely close points on the curve. More precisely, a straight line is said to be a tangent of a curve y = f(x) at a point x = c on the curve if the line passes through the point (c, f(c)) on the curve and has slope f'(c), where f' is the derivative of f.
____


[latexmath]
++++
include::assets/tangent-line.tex[]
++++

