// :autofit-option:
:stem: latexmath
:toc:

= Derivatives


ifeval::["{docname}{outfilesuffix}" == "derivatives.html"]
++++
include::../assets/navigation.htm[]
++++
endif::[]


== Overview

[latexmath]
++++
f^\prime(x) =
\lim_{h \to 0} \frac{f(a + h) - f(a)}{h} =
\lim_{x \to a} \frac{f(a) - f(x)}{a - x} =
\frac{dy}{dx}f(x) =
\frac{d}{dx}f(x)
++++

== Formal Limit Definition of A Derivative

=== Example

**Derivative of latexmath:[f(x)=|x|] using the formal limit definition of a derivative**:

[latexmath]
++++
\begin{equation}
\begin{split}
f(x) & = |x| \\
f^\prime(a) & = \lim_{h \to 0} \frac{f(a + h) - f(a)}{h} \\
     & = \lim_{h \to 0} \frac{|a + h| - |a|}{h} \cdot \frac{|a + h| + |a|}{|a + h| + |a|} \\
     & = \lim_{h \to 0} \frac{|a + h|^2 - |a|^2}{h \cdot (|a + h| + |a|)} \\
     & = \lim_{h \to 0} \frac{(a + h)^2 - a^2}{h (|a + h| + |a|)} \\
     & = \lim_{h \to 0} \frac{a^2 + 2ah + h^2 - a^2}{h (|a + h| + |a|)} \\
     & = \lim_{h \to 0} \frac{2ah + h^2}{h (|a + h| + |a|)} \\
     & = \lim_{h \to 0} \frac{h \cdot (2a + h)}{h \cdot (|a + h| + |a|)} \\
     & = \lim_{h \to 0} \frac{2a + h}{|a + h| + |a|} \\
     & = \frac{2a + (0)}{|a + (0)| + |a|} \\
     & = \frac{2a}{|a| + |a|} \\
     & = \frac{2a}{2|a|} \\
     & = \frac{2a}{2|a|} \cdot \frac{|a|}{|a|} \\
     & = \frac{2a|a|}{2|a|^2} \\
     & = \frac{2a|a|}{2a^2} \\
     & = \frac{|a|}{a} \\
f^\prime(x) &= \frac{|x|}{x}
\end{split}
\end{equation}
++++

**Derivative of latexmath:[f(x)=|x|] using an alternative limit definition of a derivative**:

[latexmath]
++++
\begin{equation}
\begin{split}
f(x) & = |x| \\
f^\prime(a) & = \lim_{x \to a} \frac{f(a) - f(x)}{a - x} \\
    & = \lim_{x \to a} \frac{|a| - |x|}{a - x} \cdot \frac{|a| + |x|}{|a| + |x|} \\
    & = \lim_{x \to a} \frac{|a|^2 - |x|^2}{(a - x) \cdot (|a| + |x|)} \\
    & = \lim_{x \to a} \frac{(a)^2 - (x)^2}{(a - x) \cdot (|a| + |x|)} \\
    & = \lim_{x \to a} \frac{(a - x) \cdot (a + x)}{(a - x) \cdot (|a| + |x|)} \\
    & = \lim_{x \to a} \frac{a + x}{|a| + |x|} \\
    & = \frac{a + (a)}{|a| + |(a)|} \\
    & = \frac{2a}{2|a|} \\
    & = \frac{a}{|a|} \cdot \frac{|a|}{|a|} \\
    & = \frac{a|a|}{|a|^2} \\
    & = \frac{a|a|}{a^2} \\
    & = \frac{|a|}{a} \\
f^\prime(x) &= \frac{|x|}{x}
\end{split}
\end{equation}
++++


== Derivative Continuity

Is a derivative continuous at latexmath:[x = a]?

First we ensure:
[latexmath]
++++
\lim_{x \to a^{-}} f^\prime(x) = \lim_{x \to a^{+}} f^\prime(x) = \lim_{x \to a} f^\prime(x)
++++
then:
[latexmath]
++++
\lim_{x \to a} f^\prime(x) = f^\prime(a)
++++
therefore the derivative is continuous and differentiable at latexmath:[x = a].


=== Continuous Piecewise Function

==== Example

Is this function differentiable at latexmath:[x = 2]?

[latexmath]
++++
f(x) =
\begin{cases}
    x^2 - 3 & \text{if $x \lt 2$} \\
    4x - 7 & \text{if $x \ge 2$}
\end{cases}
++++

[latexmath]
++++
f^\prime(x) =
\begin{cases}
    2x & \text{if $x \lt 2$} \\
    4 & \text{if $x \ge 2$}
\end{cases}
++++

To check:
[latexmath]
++++
\begin{equation}
\begin{split}
\lim_{x \to 2^{-}} f^\prime(x) &= 2(2) = 4 \\
\lim_{x \to 2^{+}} f^\prime(x) &= 4 \\
\text{therefore} \\
\lim_{x \to 2} f^\prime(x) &= 4 \\
\text{then we check} \\
\lim_{x \to 2} f^\prime(x) &= f^\prime(2) \\
\end{split}
\end{equation}
++++

Therefore the derivative is continuous and differentiable at latexmath:[x = 2].

== Derivatives of Trigonometric Functions

[latexmath]
++++
include::assets/derivatives-of-trig-funs.tex[]
++++


